language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t jaehyeonlim/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true jaehyeonlim/react-test-app npm run test

after_success:
  - docker build -t jaehyeonlim/docker-frontend:1.0 ./frontend
  - docker build -t jaehyeonlim/docker-backend:1.0 ./backend
  - docker build -t jaehyeonlim/docker-nginx:1.0  ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push jaehyeonlim/docker-frontend:1.0
  - docker push jaehyeonlim/docker-backend:1.0
  - docker push jaehyeonlim/docker-nginx:1.0

deploy:
  provider: elasticbeanstalk
  region: ap-northeast-2
  app: docker-fullstack-app
  env: Dockerfullstackapp-env
  bucket: elasticbeanstalk-ap-northeast-2-147255860737
  bucket_path: docker-fullstack-app
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
